name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        uses: nrwl/nx-set-shas@v3
      - run: |
          npm ci
          npx nx affected -t build --parallel=3

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build